image: docker.taujhe.de/build/libmumble_client

stages:
  - build
  - test

build:
  stage: build
  script:
    - rm -rf build
    - mkdir build
    - cd build
    - cmake -G Ninja ..
    - cmake --build . --parallel --clean-first
  artifacts:
    paths:
      - build/

# run tests using the binary built before
test:
  stage: test
  script:
    - cd build
    - ctest
