image: docker.taujhe.de/build/libmumble_client

stages:
  - build
  - test

build:
  stage: build
  cache:
    key: build-cache
    paths:
      - build/
  script:
    - mkdir build && cd build
    - cmake -G Ninja ..
    - cmake --build . --parallel --clean-first
  artifacts:
    paths:
      - build/**/*.so*

# run tests using the binary built before
test:
  stage: test
  cache:
    key: build-cache
  script:
    - cd build
    - cmake -G Ninja ..
    - ctest
